# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140213194937296
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
array1 = np.arange(10)
print(array1.nbytes)

80


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null2 = np.zeros(10)
null2[4] = 1
print(null2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
array2 = np.arange(50)
print(array2[10:50])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
array2_desc = np.sort(array2[10:50])[::-1]
print(array2_desc)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
array3 = np.arange(9)
print(array3.reshape(3, 3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
array4 = np.array([1, 2, 0, 0, 4, 0])
indices = np.arange(len(array4))

print(indices[array4 != 0])

[0 1 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
I_matrix = np.identity(3)
print(I_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
random_arr = np.random.random((3, 3, 3))
print(random_arr)

[[[0.01314671 0.96169425 0.47154907]
  [0.04777003 0.82404656 0.99573244]
  [0.45633716 0.48065988 0.11228716]]

 [[0.67535785 0.80131537 0.78855467]
  [0.95521604 0.16174466 0.35119779]
  [0.34868775 0.10510312 0.66563493]]

 [[0.4460362  0.87378365 0.64269587]
  [0.80161742 0.54022802 0.0520566 ]
  [0.53190474 0.54073401 0.56903319]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
random_arr2 = np.random.random((10, 10))
print(random_arr2)
print("max:", np.max(random_arr2), "min:", np.min(random_arr2))

[[0.0069717  0.11043789 0.79063749 0.38918719 0.19487282 0.75170898
  0.24820183 0.15939248 0.9698194  0.76685635]
 [0.01583924 0.4169108  0.03357189 0.69775352 0.76041246 0.46969353
  0.06538565 0.65976626 0.17166646 0.11612184]
 [0.63585537 0.79139911 0.61721738 0.94836578 0.79707043 0.78357521
  0.38997542 0.3650171  0.00991749 0.25061115]
 [0.89220743 0.87655777 0.32599031 0.27925804 0.51326845 0.39321722
  0.54129118 0.28409556 0.21994469 0.72310532]
 [0.23734156 0.30884072 0.1865372  0.38773673 0.98754835 0.02309363
  0.50677216 0.07847039 0.07878606 0.73761648]
 [0.15319031 0.18029947 0.8252434  0.92605602 0.42482132 0.352847
  0.69380369 0.69803729 0.28702553 0.2325934 ]
 [0.900688   0.20256114 0.54228687 0.7211966  0.54907255 0.67463801
  0.89216453 0.61908487 0.24218631 0.93440461]
 [0.53956728 0.64990584 0.71568119 0.85249846 0.20991984 0.79166695
  0.57258491 0.68482    0.97089095 0.70389633]
 [0.41150723 0.64586823 0.57847364 0.75704443 0.16919386 0.23156814
  0.32006933 0

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
random_arr3 = np.random.random(30)
print(random_arr3)
print("mean:", np.mean(random_arr3))

[0.70569945 0.13511018 0.18152387 0.33748475 0.7223592  0.13046329
 0.49792468 0.02601718 0.25678609 0.88780984 0.878644   0.68216022
 0.79199622 0.32688094 0.29315147 0.91480219 0.35831818 0.44340159
 0.90471633 0.31151236 0.26941785 0.80620721 0.59044779 0.75655087
 0.36624823 0.3516328  0.30582407 0.16150129 0.97061808 0.08042832]
mean: 0.48152128456436183


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
array5 = np.zeros((5, 5), dtype=int)

array5[0, :] = 1
array5[-1, :] = 1
array5[:, 0] = 1
array5[:, -1] = 1

print(array5)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, True

nan은 계산 결과를 예측할 수 없는 특수한 값을 의미한다.
따라서 0을 곱하는 것을 포함해 어떤 사칙연산을 해도 nan이 유지되며, nan이라고 해도 모두 같은 값을 의미하지 않는다. 또한 비교할 수 없으므로 항상 false의 결과가 나오기 때문에 무한대 inf와 비교해도 false 결과를 갖는다. 그러나 집합 내에서는 해시값을 기반으로 판단하며, nan은 집합 내에서 동일한 해시값을 가지므로 True가 결과로 도출된다. 0.1은 이진수로 정확하게 표현할 수 없는 값이므로, 파이썬에서 연산하면 미세한 오차가 발생하기 때문에 3을 곱했을 때 0.3이라고 볼 수 없다.

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
arr = np.zeros((5, 5))

arr[np.arange(1, 5), np.arange(0, 4)] = [1, 2, 3, 4]

print(arr)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
checkerboard = np.zeros((4, 4))

checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
arr3d = (6, 7, 8)
index = np.unravel_index(99, arr3d)
print(index)

(1, 5, 3)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
X = np.random.rand(5, 5)

X_bar = np.mean(X)
X_std = np.std(X)
Z = (X-X_bar)/X_std

print("random matrix:", X)
print("normalized matrix:", Z)

random matrix: [[0.43071309 0.34099022 0.72279572 0.54516501 0.57021346]
 [0.66487928 0.16182512 0.83455736 0.14172627 0.93986935]
 [0.0909227  0.56649059 0.76096577 0.98471532 0.93804077]
 [0.77568655 0.63526288 0.75358929 0.82039405 0.74812134]
 [0.29436315 0.7961935  0.75494845 0.80291045 0.99190395]]
normalized matrix: [[-0.81985186 -1.16686868  0.30982202 -0.37719171 -0.28031301]
 [ 0.08582139 -1.85981692  0.74207712 -1.93755225  1.14938722]
 [-2.13404277 -0.29471181  0.45745047  1.32283582  1.14231488]
 [ 0.51438532 -0.02872455  0.42892081  0.68729838  0.40777268]
 [-1.34720598  0.59369906  0.43417757  0.61967788  1.35063893]]


20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
color_dtype = np.dtype([
    ('R', np.ubyte),
    ('G', np.ubyte),
    ('B', np.ubyte),
    ('A', np.ubyte)
])