#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [47]:
import numpy as np

A = np.random.random((5, 3))
B = np.random.random((3, 2))

print(np.dot(A, B))

[[0.79394619 0.40630572]
 [1.43341895 0.82281789]
 [0.77354419 0.46951939]
 [0.71116103 0.23377017]
 [0.36739031 0.37953761]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [48]:
arr = np.arange(10)
arr[(arr>3)&(arr<8)] *= -1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [49]:
print(sum(range(5),-1))

10


In [50]:
from numpy import *
print(sum(range(5),-1))

10


첫 번째 줄은 0+1+2+3+4 - 1 =9
두 번째 줄에서 numpy에 *을 import 함으로써 세 번째 줄의 -1이 축이 되어 0+1+2+3+4 = 10

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

1,2,4,5 -> legal 3,6 -> illegal


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-40-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-40-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-40-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

print(Z1)
print(Z2)
print(np.unique(Z1[np.isin(Z1, Z2)]))

[7 1 9 1 2 5 5 3 1 5]
[4 3 9 9 0 8 4 7 6 7]
[3 7 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False. np.sqrt(-1)은 음수일 경우 nan을 출력하나, np.emath.sqrt(-1)은 복소수 계산으로 1j 출력함


#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [ ]:
Z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [ ]:
A=np.random.randint(10)
B=np.random.randint(10)
C=np.add(A,B)
D=np.negative(A)
E=np.divide(D,2)
F=np.multiply(A,E)
print(F)

-2.0


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [ ]:
A=np.random.uniform(0,10,5)
print(A//1)

[3. 3. 6. 6. 3.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
A=np.random.randint(0,5,25).reshape((5,5))
print(A)

[[2 1 3 2 1]
 [0 0 4 2 1]
 [3 0 2 2 2]
 [1 1 0 0 1]
 [1 1 1 1 2]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
A=np.random.randint(0,10,10)
print(A)
print(np.sort(A))

[9 7 4 8 2 1 6 5 9 2]
[1 2 2 4 5 6 7 8 9 9]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [ ]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
equal = np.array_equal(A, B)
print(equal)

False


부동소수점까지 동일하지 않기 때문에 False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [ ]:
cartesian = np.random.rand(10, 2)
print("cartesian coordinates:\n", cartesian)

x = cartesian[:, 0]
y = cartesian[:, 1]

r = np.sqrt(x**2 + y**2) #반지름r
theta = np.arctan2(y, x) #각도 계산

polar_coordinates = np.column_stack((r, theta))
print("\n극좌표 (r, theta):\n", polar_coordinates)

cartesian coordinates:
 [[0.86988154 0.13172957]
 [0.14404978 0.01453067]
 [0.94912232 0.79899253]
 [0.7480683  0.39822341]
 [0.83787003 0.40135499]
 [0.36241615 0.42845451]
 [0.07319103 0.5879197 ]
 [0.79006724 0.41226279]
 [0.6514672  0.66338923]
 [0.90683388 0.92168403]]

극좌표 (r, theta):
 [[0.87979917 0.15029201]
 [0.1447808  0.10053251]
 [1.24065395 0.69972741]
 [0.84745977 0.48918025]
 [0.92903822 0.44672171]
 [0.56117621 0.86870574]
 [0.59245802 1.44694199]
 [0.89116039 0.4809408 ]
 [0.92978211 0.79446509]
 [1.29300006 0.7935194 ]]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [ ]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.74571922 0.         0.49880947 0.26632567 0.17768927 0.52798714
 0.62975038 0.53458016 0.61569761 0.43400765]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()     #Z-v의 절댓값의 array의 가장 작은 값의 index return
print(Z[index])

48


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [ ]:
Z = np.arange(9).reshape(3,3)
# 방법1
for index, value in np.ndenumerate(Z):
    print(index, value)
# 방법2
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [51]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [52]:
Z = np.random.randint(0,10,(3,3))
print("기존 배열:\n", Z)

기존 배열:
 [[0 3 9]
 [1 2 5]
 [0 3 4]]


In [53]:
#column 1
print(Z)
print(Z[Z[:,0].argsort()])

[[0 3 9]
 [1 2 5]
 [0 3 4]]
[[0 3 9]
 [0 3 4]
 [1 2 5]]


In [54]:
#column 2
print(Z)
print(Z[Z[:,1].argsort()])

[[0 3 9]
 [1 2 5]
 [0 3 4]]
[[1 2 5]
 [0 3 9]
 [0 3 4]]


In [55]:
#column 3
print(Z)
print(Z[Z[:,2].argsort()])

[[0 3 9]
 [1 2 5]
 [0 3 4]]
[[0 3 4]
 [1 2 5]
 [0 3 9]]
